// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskApi.DataAcses;

namespace TaskApi.DataAcses.Migrations
{
    [DbContext(typeof(TodoDbcontext))]
    [Migration("20231208090017_newFieldsAndAnotation")]
    partial class newFieldsAndAnotation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TaskApi.Models.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AddrssNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AddrssNo = "50",
                            FullName = "kaveesha",
                            city = "Colombo 1",
                            street = "street 1"
                        },
                        new
                        {
                            id = 2,
                            AddrssNo = "60",
                            FullName = "Thathsara",
                            city = "Colombo 2",
                            street = "street 2"
                        },
                        new
                        {
                            id = 3,
                            AddrssNo = "70",
                            FullName = "Sandaru",
                            city = "Colombo 3",
                            street = "street 3"
                        },
                        new
                        {
                            id = 4,
                            AddrssNo = "80",
                            FullName = "Nimesh",
                            city = "Colombo 4",
                            street = "street 4"
                        });
                });

            modelBuilder.Entity("TaskApi.Models.Todo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Authorid")
                        .HasColumnType("int");

                    b.Property<DateTime>("create")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("due")
                        .HasColumnType("datetime2");

                    b.Property<int>("ststus")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.HasIndex("Authorid");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Authorid = 1,
                            create = new DateTime(2023, 12, 8, 14, 30, 17, 510, DateTimeKind.Local).AddTicks(8011),
                            description = "Get books fro the School new",
                            due = new DateTime(2023, 12, 13, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4107),
                            ststus = 0,
                            title = "Gets book new from SQl"
                        },
                        new
                        {
                            id = 2,
                            Authorid = 1,
                            create = new DateTime(2023, 12, 8, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4666),
                            description = "Get spare arts for vehichel new",
                            due = new DateTime(2023, 12, 12, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4669),
                            ststus = 0,
                            title = "Get car parts new from Sql"
                        },
                        new
                        {
                            id = 3,
                            Authorid = 2,
                            create = new DateTime(2023, 12, 8, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4673),
                            description = "Get foods for the week new",
                            due = new DateTime(2023, 12, 11, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4674),
                            ststus = 0,
                            title = "Get Food New from Sql"
                        },
                        new
                        {
                            id = 4,
                            Authorid = 3,
                            create = new DateTime(2023, 12, 8, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4676),
                            description = "Get medicine Hosptiale new",
                            due = new DateTime(2023, 12, 9, 14, 30, 17, 511, DateTimeKind.Local).AddTicks(4676),
                            ststus = 0,
                            title = "Get Medicine new from Sql"
                        });
                });

            modelBuilder.Entity("TaskApi.Models.Todo", b =>
                {
                    b.HasOne("TaskApi.Models.Author", "Author")
                        .WithMany("todos")
                        .HasForeignKey("Authorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskApi.Models.Author", b =>
                {
                    b.Navigation("todos");
                });
#pragma warning restore 612, 618
        }
    }
}
